"""empty message

Revision ID: e5c4289a8a8e
Revises: 0ec8189ce5f0
Create Date: 2024-06-15 20:30:53.610605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5c4289a8a8e'
down_revision = '0ec8189ce5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=True))
        batch_op.drop_index('nombre')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('precio')
        batch_op.drop_column('categoria')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('descripcion', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('categoria', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('precio', mysql.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('nombre', ['nombre'], unique=True)
        batch_op.drop_column('category')
        batch_op.drop_column('image')
        batch_op.drop_column('description')
        batch_op.drop_column('price')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
